apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: petclinic-dev

bases:
  - ../../base

resources:
  - namespace.yaml
  - petclinic-deployment.yaml

images:
  - name: image-registry.openshift-image-registry.svc:5000/petclinic-dev/petclinic-app:latest
    newTag: petclinic-dev

