apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    alpha.image.policy.openshift.io/resolve-names: '*'
    app.openshift.io/vcs-ref: ""
    app.openshift.io/vcs-uri: https://github.com/kneal-redhat/spring-petclinic
    deployment.kubernetes.io/revision: "2"
    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"petclinic-app:latest","namespace":"petclinic-dev"},"fieldPath":"spec.template.spec.containers[?(@.name==\"petclinic-app\")].image","pause":"false"}]'
    openshift.io/generated-by: OpenShiftWebConsole
  labels:
    app: petclinic-app
    app.kubernetes.io/component: petclinic-app
    app.kubernetes.io/instance: petclinic-app
    app.kubernetes.io/name: petclinic-app
    app.kubernetes.io/part-of: petclinic
    app.openshift.io/runtime: java
    app.openshift.io/runtime-version: openjdk-11-el7
  name: petclinic-app
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: petclinic-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: petclinic-app
        deploymentconfig: petclinic-app
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/petclinic-dev/petclinic-app:latest
        imagePullPolicy: Always
        name: petclinic-app
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8443
          protocol: TCP
        - containerPort: 8778
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
